orbs:
  slack: circleci/slack@3.4.2

# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.18.3

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/test

    steps:
      - checkout
      - setup_remote_docker

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "./package.json" }}

      - run: yarn run lint

      - run: yarn run test

      - run: npx codecov

      - run: curl -s -L https://gist.githubusercontent.com/u-minor/8cb27fa9c04163142ebd/raw/circleci-coverage-slack | bash -s

      - run: yarn run build

      - slack/status:
          success_message: ':ok: Branch: $CIRCLE_BRANCH\n:github: User: $CIRCLE_USERNAME'
          failure_message: ':no_good: $CIRCLE_BRANCH\n:github: User: $CIRCLE_USERNAME'
          webhook: '${SLACK_WEBHOOK}'
